spring:
  datasource:
    url: ${DB_URL:jdbc:pgsql://localhost:5432/dashboard_dev}
    driverClassName: ${DB_DRIVER:com.impossibl.postgres.jdbc.PGDriver}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        enable_lazy_load_no_trans: true
